// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace vanb.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220626172423_remove_complex_key")]
    partial class remove_complex_key
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Models.TecajRazmjene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrojTecajnice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatumPrimjene")
                        .HasColumnType("TEXT");

                    b.Property<string>("Drzava")
                        .HasColumnType("TEXT");

                    b.Property<string>("DrzavaIso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jedinica")
                        .HasColumnType("TEXT");

                    b.Property<string>("KupovniTecaj")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdajniTecaj")
                        .HasColumnType("TEXT");

                    b.Property<string>("SifraValute")
                        .HasColumnType("TEXT");

                    b.Property<string>("SrednjiTecaj")
                        .HasColumnType("TEXT");

                    b.Property<string>("Valuta")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TecajiRazmjene");
                });
#pragma warning restore 612, 618
        }
    }
}
